<a href="https://colab.research.google.com/github/rajnishkumar1906/Deep-Learning/blob/main/NNmodule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torchinfo

# **TRAINING PIPELINE WITH THE HELP OF NN MODULE**

Single neuron - neural network

In [ ]:
from torch import nn
import torch

In [ ]:
class Model(nn.Module):
  def __init__(self,features):
    super().__init__()
    self.linear = nn.Linear(features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,x):
    out = self.linear(x)
    out = self.sigmoid(out)
    return out

In [ ]:
# Create dataset
features = torch.rand(10,5)

# Assigning dataset to model
model = Model(features.shape[1])

# Applying forward pass
model(features)        # Instead of model.forward(features) we use model(features)

tensor([[0.6667],
        [0.6132],
        [0.6674],
        [0.6972],
        [0.6748],
        [0.6988],
        [0.6900],
        [0.6808],
        [0.7027],
        [0.7145]], grad_fn=<SigmoidBackward0>)

In [ ]:
# Get the model weight
model.linear.weight

Parameter containing:
tensor([[-0.1328,  0.4077,  0.0211,  0.4082,  0.0188]], requires_grad=True)

In [ ]:
# Get the midel bias
model.linear.bias

Parameter containing:
tensor([0.3245], requires_grad=True)

In [ ]:
# Get the summary of the model and dataset
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Multi-Layered Neural Network

In [ ]:
class Multi_Layered_Model(nn.Module):
  def __init__(self,features):
    super().__init__()
    self.linear1 = nn.Linear(features,3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):  # use 'x' to match the convention
      out = self.linear1(x)
      out = self.relu(out)
      out = self.linear2(out)
      out = self.sigmoid(out)
      return out

In [ ]:
# Create dataset
features = torch.rand(20,10)

# Model initializing
Model = Multi_Layered_Model(features.shape[1])

# Applying forward pass
Model(features)

tensor([[0.4692],
        [0.4814],
        [0.4692],
        [0.4692],
        [0.4581],
        [0.4788],
        [0.4790],
        [0.4708],
        [0.4692],
        [0.4692],
        [0.4692],
        [0.4692],
        [0.4620],
        [0.4645],
        [0.4692],
        [0.4692],
        [0.4692],
        [0.4869],
        [0.4756],
        [0.4692]], grad_fn=<SigmoidBackward0>)

In [ ]:
Model.linear1.weight

Parameter containing:
tensor([[-0.2953, -0.1420, -0.1350, -0.1852,  0.1651,  0.1965, -0.1320,  0.1357,
         -0.0852,  0.1852],
        [-0.2088, -0.2412, -0.0886,  0.3145,  0.1467,  0.1295, -0.1921,  0.0349,
         -0.0279, -0.0064],
        [-0.0863, -0.1059, -0.1296, -0.0902,  0.0557,  0.1833, -0.2747,  0.2638,
          0.1265, -0.0871]], requires_grad=True)

In [ ]:
Model.linear2.weight

Parameter containing:
tensor([[ 0.4490,  0.3167, -0.4951]], requires_grad=True)

In [ ]:
Model.linear1.bias

Parameter containing:
tensor([ 0.1510, -0.0873, -0.0125], requires_grad=True)

In [ ]:
Model.linear2.bias

Parameter containing:
tensor([-0.1232], requires_grad=True)

In [ ]:
summary(Model,input_size=(20,10))

Layer (type:depth-idx)                   Output Shape              Param #
Multi_Layered_Model                      [20, 1]                   --
├─Linear: 1-1                            [20, 3]                   33
├─ReLU: 1-2                              [20, 3]                   --
├─Linear: 1-3                            [20, 1]                   4
├─Sigmoid: 1-4                           [20, 1]                   --
Total params: 37
Trainable params: 37
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Using sequential containers for layers

In [ ]:
class Sequaltial_Model(nn.Module):
  def __init__(self,features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self, x):
      out = self.network(x)
      return out

In [ ]:
model = Sequaltial_Model(features.shape[1])
model(features)

tensor([[0.6136],
        [0.6134],
        [0.6169],
        [0.6136],
        [0.6134],
        [0.6233],
        [0.6256],
        [0.6134],
        [0.6134],
        [0.6137],
        [0.6134],
        [0.6152],
        [0.6222],
        [0.6210],
        [0.6134],
        [0.6157],
        [0.6138],
        [0.6174],
        [0.6158],
        [0.6140]], grad_fn=<SigmoidBackward0>)

# AUTOGRAD

In [ ]:
import torch

In [ ]:
x = torch.tensor(4.0,requires_grad=True)
x

tensor(4., requires_grad=True)

In [ ]:
y = x**3
y

tensor(64., grad_fn=<PowBackward0>)

In [ ]:
# To get the derivative
y.backward()

In [ ]:
x.grad    #finally got the derivate of y w.r.t x by in back flow with the help of autograd

tensor(48.)

Dealing with derivative of complex functions

In [ ]:
x = torch.tensor(3.1432,requires_grad=True)
x

tensor(3.1432, requires_grad=True)

In [ ]:
y = x**3 + torch.sin(x)

In [ ]:
y

tensor(31.0523, grad_fn=<AddBackward0>)

In [ ]:
y.backward()

x.grad

tensor(28.6391)