<a href="https://colab.research.google.com/github/rajnishkumar1906/Deep-Learning/blob/main/RNNpipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Connecting google colab to gogle drive to get dataset

In [163]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Importing library

In [164]:
import pandas as pd

# Load Dataset

In [162]:
df = pd.read_csv("/content/drive/MyDrive/DATASETS/BreastCancerdetection.csv")
df.head(10)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   
5    843786         M        12.45         15.70           82.57      477.1   
6    844359         M        18.25         19.98          119.60     1040.0   
7  84458202         M        13.71         20.83           90.20      577.9   
8    844981         M        13.00         21.82           87.50      519.8   
9  84501001         M        12.46         24.04           83.97      475.9   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760         0.30010              0.14710   
1          0.08474           0.07864         0.08690              0.07017   
2          0.10960           0.15990         0.19740              0.12790   
3          0.14250           0.28390         0.24140              0.10520   
4          0.10030           0.13280         0.19800              0.10430   
5          0.12780           0.17000         0.15780              0.08089   
6          0.09463           0.10900         0.11270              0.07400   
7          0.11890           0.16450         0.09366              0.05985   
8          0.12730           0.19320         0.18590              0.09353   
9          0.11860           0.23960         0.22730              0.08543   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   
5  ...          23.75           103.40       741.6            0.1791   
6  ...          27.66           153.20      1606.0            0.1442   
7  ...          28.14           110.60       897.0            0.1654   
8  ...          30.73           106.20       739.3            0.1703   
9  ...          40.68            97.65       711.4            0.1853   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   
5             0.5249           0.5355                0.1741          0.3985   
6             0.2576           0.3784                0.1932          0.3063   
7             0.3682           0.2678                0.1556          0.3196   
8             0.5401           0.5390                0.2060          0.4378   
9             1.0580           1.1050                0.2210          0.4366   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  
5                  0.12440          NaN  
6                  0.08368          NaN  
7                  0.11510          NaN  
8                  0.10720          NaN  
9                  0.20750          NaN  

[10 rows x 33 columns]

In [165]:
df.shape

(569, 33)

# Deleting unwanted dataset column

In [166]:
df.drop(["id","Unnamed: 32"],axis=1,inplace=True)
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

# Data Preprocessing

Splitting dataset

In [167]:
# Train and test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

Normalizing dataset

In [168]:
# Normalize the dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [169]:
X_train

array([[-0.81828551, -2.02270874, -0.81235046, ..., -0.420355  ,
         0.16604709,  0.07062663],
       [-1.62767848, -1.48422362, -1.58921334, ..., -0.48823836,
         0.11160096,  1.14387052],
       [-0.63297187, -0.11439305, -0.67523272, ..., -1.00862673,
        -0.05833695, -0.16944826],
       ...,
       [-0.99219524,  0.61303422, -1.00026785, ..., -0.64455274,
         0.08190308, -0.39915629],
       [-1.37280094,  0.38394186, -1.35875641, ..., -0.79188703,
        -0.06163671,  0.44601646],
       [ 1.57368594,  0.51383959,  1.51534712, ...,  0.9863222 ,
         0.25514075, -0.07560081]])

In [170]:
y_train

120    B
525    B
346    B
334    B
253    M
      ..
267    B
234    B
427    B
66     B
218    M
Name: diagnosis, Length: 455, dtype: object

Applying label encoder on target variable to get categorial data into numerical values

In [171]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

y_train

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,

Converting numpy dataset into torch tesors

In [172]:
import torch
X_train_tensor = torch.tensor(X_train,dtype=torch.float32)
X_test_tensor = torch.tensor(X_test,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test,dtype=torch.float32)

# Defining model

In [173]:
import torch
from torch.nn.functional import binary_cross_entropy

class MySimpleNN():
    def __init__(self, X):
        self.weight = torch.randn(X.shape[1], 1, requires_grad=True)
        self.bias = torch.zeros(1, requires_grad=True)

    def forward(self, X):
        out = torch.matmul(X, self.weight) + self.bias
        out = torch.sigmoid(out)
        return out

    def loss_function(self, y_pred, target):
        return binary_cross_entropy(y_pred, target)

    def backprop(self, loss, learning_rate):
        # Calculate gradients
        loss.backward()
        # Update parameters
        with torch.no_grad():
            self.weight -= learning_rate * self.weight.grad
            self.bias -= learning_rate * self.bias.grad
        # Zero gradients for next iteration
        self.weight.grad.zero_()
        self.bias.grad.zero_()

In [174]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [175]:
# Create model
model = MySimpleNN(X_train_tensor)
model.weight

tensor([[ 0.0680],
        [-0.2208],
        [-0.6986],
        [ 0.8466],
        [-2.3426],
        [ 0.6136],
        [-2.3235],
        [-0.3599],
        [-1.4852],
        [ 0.3131],
        [-0.1015],
        [ 0.8101],
        [-0.5350],
        [ 1.1875],
        [ 1.2900],
        [-0.0169],
        [-1.2237],
        [-0.9815],
        [ 0.2071],
        [ 0.9766],
        [-0.4859],
        [-1.3161],
        [-1.5356],
        [ 0.8859],
        [-0.0885],
        [-0.2848],
        [ 0.4139],
        [-0.3016],
        [-0.5389],
        [ 0.6436]], requires_grad=True)

In [176]:
model.bias

tensor([0.], requires_grad=True)

In [177]:
for epoch in range(epochs):
    # Forward pass
    y_pred = model.forward(X_train_tensor)
    # Compute loss
    loss = model.loss_function(y_pred, y_train_tensor.unsqueeze(1))
    # Print progress
    print(f"Epoch : {epoch+1}  ,  Loss : {loss.item()}")
    # Backpropagation and parameter update
    model.backprop(loss, learning_rate)

Epoch : 1  ,  Loss : 5.349031448364258
Epoch : 2  ,  Loss : 4.443970203399658
Epoch : 3  ,  Loss : 3.7565362453460693
Epoch : 4  ,  Loss : 3.1244423389434814
Epoch : 5  ,  Loss : 2.5707414150238037
Epoch : 6  ,  Loss : 2.1026768684387207
Epoch : 7  ,  Loss : 1.7249476909637451
Epoch : 8  ,  Loss : 1.4288614988327026
Epoch : 9  ,  Loss : 1.199241042137146
Epoch : 10  ,  Loss : 1.023523211479187
Epoch : 11  ,  Loss : 0.8911218047142029
Epoch : 12  ,  Loss : 0.7919562458992004
Epoch : 13  ,  Loss : 0.7164334058761597
Epoch : 14  ,  Loss : 0.6570239663124084
Epoch : 15  ,  Loss : 0.608837366104126
Epoch : 16  ,  Loss : 0.5688262581825256
Epoch : 17  ,  Loss : 0.5349972248077393
Epoch : 18  ,  Loss : 0.5059788823127747
Epoch : 19  ,  Loss : 0.48078152537345886
Epoch : 20  ,  Loss : 0.45867079496383667
Epoch : 21  ,  Loss : 0.43908780813217163
Epoch : 22  ,  Loss : 0.42160630226135254
Epoch : 23  ,  Loss : 0.40588849782943726
Epoch : 24  ,  Loss : 0.3916657567024231
Epoch : 25  ,  Loss : 0.3

# Model Evaluation

In [178]:
import torch
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

with torch.no_grad():
    y_pred_probs = model.forward(X_test_tensor)
    y_pred_labels = torch.where(y_pred_probs > 0.5, 1, 0)

predicted = y_pred_labels.cpu().numpy()
true = y_test_tensor.cpu().numpy()

accuracy = accuracy_score(true, predicted)
precision = precision_score(true, predicted)
recall = recall_score(true, predicted)
f1 = f1_score(true, predicted)

print(f"Test Accuracy: {accuracy:.2f}")
print(f"Test Precision: {precision:.2f}")
print(f"Test Recall: {recall:.2f}")
print(f"Test F1-score: {f1:.2f}")

Test Accuracy: 0.85
Test Precision: 0.75
Test Recall: 0.77
Test F1-score: 0.76
